services:
  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - app

  api:
    image: ghcr.io/jatin34090/storebuilder-api:latest

    restart: always
    env_file: .env.production
    environment:
      NODE_ENV: production
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - redis
    networks:
      - app

  web:
    image: ghcr.io/jatin34090/storebuilder-web:latest
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
      NEXT_PUBLIC_ROOT_DOMAIN: storebuilder.jatsolutions.in
      API_URL: http://api:3001/api/v1
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - app

volumes:
  redis_data:

networks:
  app:
    driver: bridge
